# Default Markdown Language Configuration

extensions = ["md", "markdown"]

keywords = []
primitive_types = []

line_comment_start = "<!--"
block_comment_start = "<!--"
block_comment_end = "-->"
line_prefix_keyword_markers = ["# ", "## ", "### ", "#### ", "##### ", "###### ", "- ", "* ", "+ "]
line_prefix_comment_markers = ["> "]
full_line_comment_prefixes = []

[[brackets]]
open = "("
close = ")"
color_offset = 0

[[brackets]]
open = "["
close = "]"
color_offset = 1

[[brackets]]
open = "{"
close = "}"
color_offset = 2
